# Setup
title:            Modbrella | Inside-Out Umbrella
tagline:          Modern inside-out umbrellas
description:      The Modbrella is functional and innovative. It’s inverted design is easy to use and makes it stress free while you get in and out of your car, and prevents dripping by keeping water inside the umbrella when it is closed.
url:              http://modbrella.com
baseurl:          /

author:
  name:           'Modbrella'
  url:            https://modbrella.com

  time:           2016