# Setup
title:            Modbrella
tagline:          Modern inside-out umbrellas
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://modbrella.com
baseurl:          /

author:
  name:           'Modbrella'
  url:            https://modbrella.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/modbrella/modbrella.github.io
